namespace Spacious {
	struct ReminderDisplayEntry {
		String name;
		Int32 id;
	};
	
	[default_interface]
	runtimeclass ListPage: Microsoft.UI.Xaml.Controls.Page {
		Windows.Foundation.Collections.IVector<IInspectable> List {get;};
		ListPage();
	};
}