namespace Spacious {
	[default_interface]
	runtimeclass MainWindow: Microsoft.UI.Xaml.Window {
		MainWindow();
		Double TitleBarHeight {get;};
		Double TitleBarLeftPadding {get;};
		Double TitleBarRightPadding {get;};
	};
}